# -*- coding: utf-8 -*-
"""Herrera Oscar_Taller de red neuronal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135gZHZNqc38gw3QgAwmHV0OVxuAL6SMS

## Importando librerías
"""

from keras.datasets import mnist
from keras import layers, models
from keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt

"""## Nuestro set de datos"""

(train_data, train_labels), (test_data, test_labels) = mnist.load_data()

train_data.shape

test_data.shape

train_data[0]

plt.imshow(train_data[85])
plt.show

train_labels[85]

"""## Creando un modelo de datos"""

model = models.Sequential()
model.add(layers.Dense(512,activation='relu', input_shape=(28*28,)))
model.add(layers.Dense(10,activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

"""## Limpieza de datos"""

x_train = train_data.reshape((60000,28*28))
x_train = x_train.astype('float32')/255

x_test = test_data.reshape((10000,28*28))
x_test = x_test.astype('float32')/255

y_train = to_categorical(train_labels)
y_test = to_categorical(test_labels)

train_labels[85]

y_train[85]

"""## Entrenando el modelo"""

model.fit(x_train, y_train, epochs=5, batch_size=128)

"""## Evaluando sobre data de test"""

model.evaluate(x_test,y_test)

# from keras.utils import to_categorical

# # Lista de etiquetas (números enteros)
# labels = [0, 1, 0, 1, 0]

# # Convertir las etiquetas a representación one-hot
# one_hot_labels = to_categorical(labels)

# print(one_hot_labels)

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
import os

# 1. Cuadro de diálogo para subir las imágenes directamente
print("Por favor, selecciona y sube tus imágenes")
uploaded = files.upload()

# 2. Definición de la función
def predecir_mi_numero(path_imagen):
    # Cargar en escala de grises
    img = cv2.imread(path_imagen, cv2.IMREAD_GRAYSCALE)

    # Verificación de seguridad por si la imagen sigue sin leerse
    if img is None:
        print(f"Error: OpenCV no pudo leer la imagen '{path_imagen}'.")
        return

    # Redimensionar a 28x28 (el tamaño que espera tu red)
    img_resized = cv2.resize(img, (28, 28))

    # Invertir colores (Fondo negro, número blanco)
    img_inverted = cv2.bitwise_not(img_resized)

    # Aplanar y normalizar para Keras (1 fila, 784 columnas)
    img_final = img_inverted.reshape(1, 28*28).astype('float32') / 255

    # Predicción (Usa tu modelo ya entrenado)
    prediccion = model.predict(img_final)
    clase_predicha = np.argmax(prediccion)

    # Mostrar la imagen tal como la "ve" la red neuronal
    plt.figure(figsize=(3,3))
    plt.imshow(img_inverted, cmap='gray')
    plt.title(f"El modelo dice que es un: {clase_predicha}")
    plt.axis('off')
    plt.show()

# 3. Procesar automáticamente lo que acabas de subir
print("\n--- Iniciando predicciones ---")
for img_path in uploaded.keys():
    print(f"\nProcesando el archivo: {img_path}")
    predecir_mi_numero(img_path)