# -*- coding: utf-8 -*-
"""Copia de 1-Regresión Lineal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D5FvLTBnTzE-bmz4LmS1dLSYyj9oM9Tr

# Regresión lineal del precio de la vivienda en EE. UU.

## Primer de regresión lineal

En estadística, la regresión lineal es un enfoque lineal para modelar la relación entre una variable dependiente escalar y y una o más variables explicativas (o variables independientes) denominadas X. El caso de una variable explicativa se denomina regresión lineal simple. Para más de una variable explicativa, el proceso se denomina regresión lineal múltiple.

Los modelos de regresión lineal a menudo se ajustan utilizando el enfoque de mínimos cuadrados, pero también pueden ajustarse de otras formas, como minimizando la "falta de ajuste" en alguna otra norma (como con la regresión de desviaciones mínimas absolutas), o minimizando una penalización. versión de la función de pérdida por mínimos cuadrados como en la regresión de crestas (penalización de $L_2$ -norm) y lazo (penalización de $L_1$ -norm). Por el contrario, el enfoque de mínimos cuadrados se puede utilizar para ajustar modelos que no son modelos lineales. Por lo tanto, aunque los términos "mínimos cuadrados" y "modelo lineal" están estrechamente relacionados, no son sinónimos.

### Importando paquetes y el conjunto de datos
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

#df = pd.read_csv("https://github.com/ulewis/Ejemplos/raw/main/Datos/USA_Housing.csv")
df = pd.read_csv("https://github.com/ulewis/Ejemplos/raw/main/Datos/healthcare_dataset.csv")

df.head()  # vemos los 5 primeros datos del dataframe

label_encoders = {}
le = LabelEncoder()
df['Medical Condition'] = le.fit_transform(df['Medical Condition'].astype(str))
label_encoders['Medical Condition'] = le

"""### Consultar información básica sobre el conjunto de datos

**El método 'info()'los tipos y números de datos**
"""

df.info(verbose=True)

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Cargar datos
df = pd.read_csv("https://github.com/ulewis/Ejemplos/raw/main/Datos/healthcare_dataset.csv")

# Convertir variable necesaria
le = LabelEncoder()
df['Medical Condition'] = le.fit_transform(df['Medical Condition'].astype(str))

# Seleccionar solo 4 variables
l_column = ['Age', 'Medical Condition', 'Room Number', 'Billing Amount']
len_feature = len(l_column)

print(l_column)
print(len_feature)

"""**El método 'describe()' obtiene un resumen de estadísticas de las características del conjunto de datos**"""

df.describe()

"""**El método 'columns' obtiene los nombres de las columnas (características)**"""

df.columns

"""### Visualización básica del conjunto de datos

**Pairplots usando seaborn**
"""

sns.pairplot(df)

"""**Distribución del precio (la cantidad prevista)**"""

df['Billing Amount'].plot.hist(bins=25, figsize=(8,4))

df['Billing Amount'].plot.density()

"""**Matriz de correlación y heatmap**"""

numeric_df = df.select_dtypes(include=[np.number])
numeric_df.corr()

plt.figure(figsize=(10,7))
sns.heatmap(numeric_df.corr(),annot=True,linewidths=2)

"""### Conjuntos de características y variables

**Haga una lista de los nombres de las columnas del dataframe**
"""

l_column = list(df.columns) # Haciendo una lista de las columnas
len_feature = len(l_column) # Longitud de la lista de vectores de columna
l_column

"""**Coloque todas las características numéricas en X y el precio en y, ignore la dirección, que es una cadena para la regresión lineal**"""

X = df[['Medical Condition', 'Age']]
y = df['Billing Amount']

print("Tamaño de Características:",X.shape)
print("Tamaño de Variable Objetivo:",y.shape)

X.head()

y.head()

"""### División de entrenamiento-prueba

**Importamos la función train_test_split de scikit-learn**
"""

from sklearn.model_selection import train_test_split

"""**Creamos los conjuntos de entrenamiento X y de prueba y en un comando usando una proporción de división y una semilla aleatoria**"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123)

"""**Verifique el tamaño y la forma de las divisiones de entrenamiento/prueba (debe estar en la proporción según el parámetro test_size anterior)**"""

print("Tamaño del conjunto de características del entrenamiento:",X_train.shape)
print("Tamaño del conjunto de características de prueba:",X_test.shape)
print("Tamaño de la variable objetivo del entrenamiento:",y_train.shape)
print("Tamaño de la variable objetivo de prueba:",y_test.shape)

"""### Ajuste y entrenamiento del modelo

**Importamos el estimador de modelo de regresión lineal de scikit-learn e lo instanciamos**
"""

from sklearn.linear_model import LinearRegression
from sklearn import metrics

lm = LinearRegression() # Creando un objeto de Regresión Lineal 'lm'

"""**Ajustamos el modelo al propio objeto instanciado**"""

lm.fit(X_train,y_train) # Ajuste el modelo lineal en el objeto 'lm' en sí, es decir, no es necesario establecer esto en otra variable

"""**Verificamos la intercepción y los coeficientes y los colocamos en un DataFrame**"""

print("El término de intersección del modelo lineal:", lm.intercept_)

print("Los coeficientes del modelo lineal:", lm.coef_)

#idict = {'Coefficients':lm.intercept_}
#idf = pd.DataFrame(data=idict,index=['Intercept'])
cdf = pd.DataFrame(data=lm.coef_, index=X_train.columns, columns=["Coefficients"])
#cdf=pd.concat([idf,cdf], axis=0)
cdf

"""### Cálculo de errores estándar y estadística t para los coeficientes"""

n=X_train.shape[0]
k=X_train.shape[1]
dfN = n-k
train_pred=lm.predict(X_train)
train_error = np.square(train_pred - y_train)
sum_error=np.sum(train_error)
se=[0]*k
for i in range(k):
    r = (sum_error/dfN)
    r = r/np.sum(np.square(X_train.iloc[:,i]-X_train.iloc[:,i].mean()))
    se[i]=np.sqrt(r)
cdf['Standard Error']=se
cdf['t-statistic']=cdf['Coefficients']/cdf['Standard Error']
cdf

print("Por lo tanto, las características organizadas en orden de importancia para predecir el precio de la vivienda\n",'-'*90,sep='')
l=list(cdf.sort_values('t-statistic',ascending=False).index)
print(' > \n'.join(l))

import matplotlib.pyplot as plt

plt.figure(figsize=(18,10))

# Gráfico 1
plt.subplot(1,2,1)
plt.scatter(df['Medical Condition'], df['Billing Amount'])
plt.title("Relación: Medical Condition vs Billing Amount", fontsize=18)
plt.xlabel("Medical Condition")
plt.ylabel("Billing Amount")

# Gráfico 2
plt.subplot(1,2,2)
plt.scatter(df['Age'], df['Billing Amount'])
plt.title("Relación: Age vs Billing Amount", fontsize=18)
plt.xlabel("Age")
plt.ylabel("Billing Amount")

plt.tight_layout()
plt.show()

"""**R cuadrado del ajuste del modelo**"""

print("Valor del R cuadrado de este ajuste:",round(metrics.r2_score(y_train,train_pred),3))

"""### Matrices de evaluación de predicción, estimación de error y regresión

**Predicción usando el modelo lm**
"""

predictions = lm.predict(X_test)
print ("Tipo del objeto predicho :", type(predictions))
print ("Tamaño del objeto predicho:", predictions.shape)

"""**Diagrama de dispersión (Scatterplot) del precio previsto y el conjunto de prueba y para ver si los datos caen en una línea recta de 45 grados**"""

plt.figure(figsize=(10,7))
plt.title("Precio de casas real vs. el predicho",fontsize=25)
plt.xlabel("Conjunto real de precios de casas",fontsize=18)
plt.ylabel("Precios predichos de casas", fontsize=18)
plt.scatter(x=y_test,y=predictions)

"""**Visualizamos el histograma de los residuos, es decir, errores predichos (se espera un patrón distribuido normalmente)**"""

plt.figure(figsize=(10,7))
plt.title("Histograma de residuos para verificar la normalidad ",fontsize=25)
plt.xlabel("Residuos",fontsize=18)
plt.ylabel("Densidad del kernel", fontsize=18)
sns.distplot([y_test-predictions])

"""**Diagrama de dispersión de residuos y valores predichos (Homoscedasticidad)**

"""

plt.figure(figsize=(10,7))
plt.title("Valores residuales vs. predichos\n",fontsize=25)
plt.xlabel("Precios predichos de casas",fontsize=18)
plt.ylabel("Residuos", fontsize=18)
plt.scatter(x=predictions,y=y_test-predictions)

"""**Métricas de evaluación de la regresión**"""

print("Mean absolute error (MAE):", metrics.mean_absolute_error(y_test,predictions))
print("Mean square error (MSE):", metrics.mean_squared_error(y_test,predictions))
print("Root mean square error (RMSE):", np.sqrt(metrics.mean_squared_error(y_test,predictions)))

"""**Valor R cuadrado**"""

print("Valor R-squared de las predicciones:",round(metrics.r2_score(y_test,predictions),3))