# -*- coding: utf-8 -*-
"""Keras_Clasificacion_binaria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y51pvRt7dulhRUVuv4Y7qo-rxnxlzT4S

## <h1><center>Clasificación binaria con Keras</center></h1>

## <center>Acerca de los datos </center>

Usaemos el conjunto de datos de 25.000 reseñas de películas de IMDB, etiquetadas por sentimiento (positivo/negativo). Las reseñas se han preprocesado y cada reseña está codificada como una lista de índices de palabras (enteros). Por conveniencia, las palabras se indexan por frecuencia general en el conjunto de datos, de modo que, por ejemplo, el número entero "3" codifica la tercera palabra más frecuente en los datos. Esto permite operaciones de filtrado rápidas como: "considerar sólo las 10.000 palabras más comunes, pero eliminar las 20 primeras palabras más comunes".

<br>

> <small> Nota: <br> Datos extraidos de : https://keras.io/api/datasets/imdb/

## Importamos librerías
"""

from keras.datasets import imdb
from keras import models, layers, optimizers
import numpy as np

"""## Descargamos los datos de imdb - Keras"""

(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000,index_from=3)

train_data[0]

train_labels[0]

"""### Diccionario de palabras"""

word_index = imdb.get_word_index()

word_index

word_index = dict([(value,key) for (key,value) in word_index.items()])
word_index

for x in train_data[0]:
    print(word_index.get(x))

"""## Función de one-hot encoding"""

def vectorizar(sequences, dim=10000):
    restults = np.zeros((len(sequences),dim))
    for i, sequences in enumerate(sequences):
        restults[i,sequences]=1
    return restults

"""## Transformamos datos"""

x_train = vectorizar(train_data)
x_test = vectorizar(test_data)

y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')

"""## Creamos el modelo"""

model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
             metrics=['accuracy'])

x_val = x_train[:10000]
partial_x_train = x_train[10000:]

y_val = y_train[:10000]
partial_y_train =  y_train[10000:]

"""## Entrenando"""

modelb = model.fit(partial_x_train,
                   partial_y_train,
                   epochs=20,
                   batch_size=512,
                   validation_data=(x_val,y_val))

"""## Analizamos resultados"""

import matplotlib.pyplot as plt

modelb_dict = modelb.history
loss_values = modelb_dict['loss']
val_loss_values = modelb_dict['val_loss']

fig = plt.figure(figsize=(10,10))
epoch = range(1,len(loss_values)+1)
plt.plot(epoch,loss_values, 'o-',label='training')
plt.plot(epoch,val_loss_values, '--',label='val')
plt.legend()
plt.show()

model.evaluate(x_test, y_test)

"""### Comparando con un modelo más pequeño"""

model2 = models.Sequential()
model2.add(layers.Dense(4, activation='relu', input_shape=(10000,)))
model2.add(layers.Dense(4, activation='relu'))
model2.add(layers.Dense(1, activation='sigmoid'))

model2.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
             metrics=['accuracy'])

modelb2 = model2.fit(partial_x_train,
                   partial_y_train,
                   epochs=20,
                   batch_size=512,
                   validation_data=(x_val,y_val))

"""## Analizamos resultados"""

import matplotlib.pyplot as plt

modelb_dict = modelb.history
loss_values = modelb_dict['loss']
val_loss_values = modelb_dict['val_loss']

val_loss_values2 = modelb2.history['val_loss']


fig = plt.figure(figsize=(10,10))
epoch = range(1,len(loss_values)+1)
plt.plot(epoch,val_loss_values2, 'o-',label='smaller')
plt.plot(epoch,val_loss_values, '--',label='original')
plt.legend()
plt.show()

"""## Regularización"""

from keras import regularizers

model3 = models.Sequential()
model3.add(layers.Dense(16, activation='relu', input_shape=(10000,),kernel_regularizer=regularizers.l2(0.001)))
model3.add(layers.Dense(16, activation='relu',kernel_regularizer=regularizers.l2(0.001)))
model3.add(layers.Dense(1, activation='sigmoid'))

model3.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
             metrics=['accuracy'])

modelb3 = model3.fit(partial_x_train,
                   partial_y_train,
                   epochs=20,
                   batch_size=512,
                   validation_data=(x_val,y_val))

import matplotlib.pyplot as plt

modelb_dict = modelb.history
loss_values = modelb_dict['loss']
val_loss_values = modelb_dict['val_loss']

val_loss_values3 = modelb3.history['val_loss']


fig = plt.figure(figsize=(10,10))
epoch = range(1,len(loss_values)+1)
plt.plot(epoch,val_loss_values3, 'o-',label='regularization')
plt.plot(epoch,val_loss_values, '--',label='original')
plt.legend()
plt.show()

"""### Dropout"""

model4 = models.Sequential()
model4.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model4.add(layers.Dropout(0.5))
model4.add(layers.Dense(16, activation='relu'))
model4.add(layers.Dropout(0.5))
model4.add(layers.Dense(1, activation='sigmoid'))

model4.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
             metrics=['accuracy'])

modelb4 = model4.fit(partial_x_train,
                   partial_y_train,
                   epochs=20,
                   batch_size=512,
                   validation_data=(x_val,y_val))

modelb_dict = modelb.history
loss_values = modelb_dict['loss']
val_loss_values = modelb_dict['val_loss']

val_loss_values4 = modelb4.history['val_loss']


fig = plt.figure(figsize=(10,10))
epoch = range(1,len(loss_values)+1)
plt.plot(epoch,val_loss_values4, 'o-',label='dropout')
plt.plot(epoch,val_loss_values, '--',label='original')
plt.legend()
plt.show()

"""### Dropout con Regularización L1 y L2"""

from keras import regularizers

model5 = models.Sequential()
# Capa densa con 16 neuronas, activación ReLU y regularización L1/L2
model5.add(layers.Dense(16, activation='relu', input_shape=(10000,), kernel_regularizer=regularizers.l1_l2(l1=0.00001, l2=0.00001)))
model5.add(layers.Dropout(0.1)) # Dropout para evitar sobreajuste
# Segunda capa densa con 16 neuronas, activación ReLU y regularización L1/L2
model5.add(layers.Dense(16, activation='relu', kernel_regularizer=regularizers.l1_l2(l1=0.00001, l2=0.00001)))
model5.add(layers.Dropout(0.1)) # Otro Dropout
model5.add(layers.Dense(1, activation='sigmoid')) # Capa de salida para clasificación binaria

# Se compila el modelo
# Optimizador 'rmsprop', función de pérdida 'binary_crossentropy', métrica 'accuracy'
model5.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
             metrics=['accuracy'])

# Entrena el modelo
# 20 épocas
modelb5 = model5.fit(partial_x_train,
                   partial_y_train,
                   epochs=20,
                   batch_size=512,
                   validation_data=(x_val,y_val))

"""## Analizamos resultados del nuevo modelo"""

import matplotlib.pyplot as plt

# Obtiene la pérdida de validación del modelo original
modelb_dict = modelb.history
val_loss_values = modelb_dict['val_loss']

# Obtiene la pérdida de validación del nuevo modelo
val_loss_values5 = modelb5.history['val_loss']

# Crea y configura el gráfico
fig = plt.figure(figsize=(10,10))
epoch = range(1,len(val_loss_values)+1)
plt.plot(epoch,val_loss_values5, 'o-',label='dropout_nuevo_l1_l2') # Grafica el nuevo modelo
plt.plot(epoch,val_loss_values, '--',label='original') # Grafica el modelo original
plt.legend()
plt.show()

"""## Predicciones"""

predictions = model.predict(x_test)

predictions[10]