# -*- coding: utf-8 -*-
"""Red_neuronal_con_Keras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eRvccUNbxZ6bAT4b-90C-cSw1FxHlYX4

## Importando librerías
"""

from keras.datasets import mnist
from keras import layers, models
from keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt

"""## Nuestro set de datos"""

(train_data, train_labels), (test_data, test_labels) = mnist.load_data()

train_data.shape

test_data.shape

train_data[0]

plt.imshow(train_data[85])
plt.show

train_labels[85]

"""## Creando un modelo de datos"""

model = models.Sequential()
model.add(layers.Dense(512,activation='relu', input_shape=(28*28,)))
model.add(layers.Dense(10,activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

"""## Limpieza de datos"""

x_train = train_data.reshape((60000,28*28))
x_train = x_train.astype('float32')/255

x_test = test_data.reshape((10000,28*28))
x_test = x_test.astype('float32')/255

y_train = to_categorical(train_labels)
y_test = to_categorical(test_labels)

train_labels[85]

y_train[85]

"""## Entrenando el modelo"""

model.fit(x_train, y_train, epochs=5, batch_size=128)

"""## Evaluando sobre data de test"""

model.evaluate(x_test,y_test)

# from keras.utils import to_categorical

# # Lista de etiquetas (números enteros)
# labels = [0, 1, 0, 1, 0]

# # Convertir las etiquetas a representación one-hot
# one_hot_labels = to_categorical(labels)

# print(one_hot_labels)

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

print("Sube tu imagen (Ahora con gráfico de probabilidades):")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# 1. Cargar y suavizar
img = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)
img_blur = cv2.GaussianBlur(img, (7, 7), 0)

# 2. detectar fondo
mediana_fondo = np.median(img_blur)

if mediana_fondo > 127:
    print("🔍 Fondo CLARO detectado. Aplicando filtro adaptativo...")
    img_thresh = cv2.adaptiveThreshold(img_blur, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                       cv2.THRESH_BINARY_INV, 21, 5)
else:
    print("🔍 Fondo OSCURO detectado. Procesando directo...")
    _, img_thresh = cv2.threshold(img_blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

# 3. ENGROSAMIENTO SIMPLE
kernel = np.ones((3,3), np.uint8)
img_cleaned = cv2.dilate(img_thresh, kernel, iterations=1)

# 4. Localizar el número
contornos, _ = cv2.findContours(img_cleaned, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
alto, ancho = img_cleaned.shape
posibles_numeros = []

for c in contornos:
    x, y, w, h = cv2.boundingRect(c)
    if x > 5 and y > 5 and (x+w) < (ancho-5) and (y+h) < (alto-5):
        if w > 15 and h > 15:
            posibles_numeros.append(c)

if posibles_numeros:
    centro_img = np.array([ancho/2, alto/2])
    def distancia_al_centro(cnt):
        m = cv2.moments(cnt)
        if m["m00"] == 0: return 10000
        cx, cy = int(m["m10"] / m["m00"]), int(m["m01"] / m["m00"])
        return np.linalg.norm(centro_img - [cx, cy])

    mejor_contorno = min(posibles_numeros, key=distancia_al_centro)
    x, y, w, h = cv2.boundingRect(mejor_contorno)
    img_recortada = img_cleaned[y:y+h, x:x+w]

    size = max(w, h)
    margen = int(size * 0.25)
    img_final = cv2.copyMakeBorder(img_recortada, margen, margen, margen, margen,
                                   cv2.BORDER_CONSTANT, value=0)
    img_final = cv2.resize(img_final, (28, 28), interpolation=cv2.INTER_AREA)
else:
    img_final = cv2.resize(img_cleaned, (28, 28))



img_input = img_final.reshape(1, 784).astype('float32') / 255
pred = model.predict(img_input, verbose=0)
probabilidades = pred[0] * 100
numero_predicho = np.argmax(pred)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

# Gráfico Izquierdo: La imagen que ve la red neuronal
ax1.imshow(img_final, cmap='gray')
ax1.set_title(f"Imagen procesada\n(La red ve un {numero_predicho})", fontsize=14)
ax1.axis('off')

# Gráfico : Histograma de Probabilidades
clases = [str(i) for i in range(10)]
barras = ax2.bar(clases, probabilidades, color='lightgray')
ax2.set_title("Probabilidades del Modelo", fontsize=14)
ax2.set_xlabel("Dígitos", fontsize=12)
ax2.set_ylabel("Confianza (%)", fontsize=12)
ax2.set_ylim(0, 110) # Límite Y hasta 110 para que entren los textos

barras[numero_predicho].set_color('limegreen')

# Colocar el texto con el % exacto encima de las barras más altas
for barra in barras:
    altura = barra.get_height()
    if altura > 1: # Solo escribir el número si la probabilidad es mayor al 1%
        ax2.annotate(f'{altura:.1f}%',
                    xy=(barra.get_x() + barra.get_width() / 2, altura),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=10, fontweight='bold')

plt.tight_layout()
plt.show()

print("\n" + "="*50)
print(f"🤖 El modelo está {probabilidades[numero_predicho]:.1f}% seguro de que escribiste el: {numero_predicho}")
print("="*50)